### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by noinoiexists** [Quantumofcosmos/Western-to-carnatic-note-converter#1]
I ran the program without modifying the ‘in.txt’ file but it does not work.
Here’s what I get:
~~~
$ cat in.txt 
E3  F3  F3#  G3  G3#  A3  A3#  B3  C4  C4#  D4  D4#  E4  F4  F4#  G4  G4#  A4  A4#  B4  

C5  C5#  D5  D5#  E5  F5  F5#  G5  G5#  A5  A5#  

B5  C6

$ python3 abc2srg.py 

$ cat out.txt 
b Z1 Z2 G#1 G#2 B1 B2 P# 
                         1 
                           2 F1 F2 S R1 R2 G1 G2 M1 M2 P 

D1 D2 N1 N2 ` X1 X2  1  2 @1 @2 

V

**Comment by Quantumofcosmos** [comment]
Hi @NithikRamesh ,
This might be because of the encoding settings of the terminal itself. Cat is trying to read UTF-16 characters as ASCII. Can you open the file with a file editor like gedit or nano and see if the problem persists.

Below is the output I get when I rerun the same snippet in windows.

```
C:\gits\Western-to-carnatic-note-converter>type out.txt
Ṣ Ṛ1 Ṛ2 G̣1 G̣2 Ṃ1 Ṃ2 P̣ Ḍ1 Ḍ2 Ṇ1 Ṇ2 S R1 R2 G1 G2 M1 M2 P

D1 D2 N1 N2 Ṡ Ṙ1 Ṙ2 Ġ1 Ġ2 Ṁ1 Ṁ2

Ṗ Ḋ1
```
